# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceurl',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sourceurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
